version: "3.9"

services:
  web:
    build: .
    command: ./EjecutarServer.sh
    ports: 
      - "8080:8080"
    volumes:
      - vigilancia:/home
    devices:
      - /dev/video0:/dev/video0



volumes: 
  vigilancia: